// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA29dzz1a2FNYVmnZ0kPOX0GHvdRcZbJPc',
    appId: '1:676969158220:web:5bde433d683373fc29c6e9',
    messagingSenderId: '676969158220',
    projectId: 'nazra-graduation',
    authDomain: 'nazra-graduation.firebaseapp.com',
    storageBucket: 'nazra-graduation.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyRqBTSkr61ywrjYmGN407nUnqyZmJLkM',
    appId: '1:676969158220:android:cd2e143f58f0b30529c6e9',
    messagingSenderId: '676969158220',
    projectId: 'nazra-graduation',
    storageBucket: 'nazra-graduation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6muOrWJ5lK13Fziqm6RGUSZmdj8zQWc4',
    appId: '1:676969158220:ios:9d69115237e6bc4529c6e9',
    messagingSenderId: '676969158220',
    projectId: 'nazra-graduation',
    storageBucket: 'nazra-graduation.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
